// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fn solve(max: u32) -> u32 {
  let mut result = 0;
  let mut tail = (1, 2);

  while tail.1 <= max {
    if tail.1 % 2 == 0 {
      result += tail.1;
    }

    tail = (tail.1, tail.0 + tail.1);
  }

  return result;
}

fn main() {
  println!("Result: {}", solve(4_000_000));
}
